// <auto-generated />
using System;
using Meetings.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meetings.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Meetings.Models.Działy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("idDzialu");

                    b.Property<int>("IdFilii")
                        .HasColumnType("int")
                        .HasColumnName("idFilii");

                    b.Property<string>("NazwaDzialu")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nazwa_Dzialu");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Id" }, "idDzialu")
                        .IsUnique();

                    b.HasIndex(new[] { "IdFilii" }, "idFilii");

                    b.ToTable("działy", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_polish_ci");
                });

            modelBuilder.Entity("Meetings.Models.Filie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("idFilii");

                    b.Property<string>("NazwaFilii")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nazwa_Filii");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NazwaFilii" }, "nazwa_Filii")
                        .IsUnique();

                    b.ToTable("filie", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_polish_ci");
                });

            modelBuilder.Entity("Meetings.Models.Grafik", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("idGrafiku");

                    b.Property<string>("DzienTygodnia")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("dzien_tygodnia");

                    b.Property<TimeOnly?>("GodzinaRozpoczecia")
                        .HasColumnType("time")
                        .HasColumnName("godzina_rozpoczecia");

                    b.Property<TimeOnly?>("GodzinaZakonczenia")
                        .HasColumnType("time")
                        .HasColumnName("godzina_zakonczenia");

                    b.Property<int>("IdPracownika")
                        .HasColumnType("int")
                        .HasColumnName("idPracownika");

                    b.Property<int?>("IloscGodzin")
                        .HasColumnType("int")
                        .HasColumnName("ilosc_godzin");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPracownika" }, "fk_idPracownika");

                    b.ToTable("grafik", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_polish_ci");
                });

            modelBuilder.Entity("Meetings.Models.Pracownik", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("idPracownika");

                    b.Property<string>("Haslo")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("haslo");

                    b.Property<int>("IdDzialu")
                        .HasColumnType("int")
                        .HasColumnName("idDzialu");

                    b.Property<int>("IdFilii")
                        .HasColumnType("int")
                        .HasColumnName("idFilii");

                    b.Property<string>("ImiePracownika")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("imie_pracownika");

                    b.Property<string>("NazwiskoPracownika")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("nazwisko_pracownika");

                    b.Property<string>("Stanowisko")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("stanowisko");

                    b.Property<bool>("admin")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdDzialu" }, "idDzialu")
                        .HasDatabaseName("idDzialu1");

                    b.HasIndex(new[] { "IdFilii" }, "idFilii")
                        .HasDatabaseName("idFilii1");

                    b.ToTable("pracownicy", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_polish_ci");
                });

            modelBuilder.Entity("Meetings.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("idSali");

                    b.Property<int?>("Pojemnosc")
                        .HasColumnType("int")
                        .HasColumnName("pojemnosc");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("sala", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_polish_ci");
                });

            modelBuilder.Entity("Meetings.Models.Spotkanie", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("idSpotkania");

                    b.Property<string>("DzienTygodnia")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("dzien_tygodnia");

                    b.Property<TimeOnly?>("GodzinaSpotkania")
                        .HasColumnType("time")
                        .HasColumnName("godzina_spotkania");

                    b.Property<int>("IdFilii")
                        .HasColumnType("int")
                        .HasColumnName("idFilii");

                    b.Property<int>("IdSali")
                        .HasColumnType("int")
                        .HasColumnName("idSali");

                    b.Property<int?>("MaxLiczbaUczestnikow")
                        .HasColumnType("int")
                        .HasColumnName("max_liczba_uczestnikow");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdFilii" }, "fk_idFilii");

                    b.HasIndex(new[] { "IdSali" }, "fk_idSali");

                    b.ToTable("spotkania", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_polish_ci");
                });

            modelBuilder.Entity("PracownicyHasSpotkanium", b =>
                {
                    b.Property<int>("IdPracownika")
                        .HasColumnType("int")
                        .HasColumnName("idPracownika");

                    b.Property<int>("IdSpotkania")
                        .HasColumnType("int")
                        .HasColumnName("idSpotkania");

                    b.HasKey("IdPracownika", "IdSpotkania")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "IdSpotkania" }, "idSpotkania");

                    b.ToTable("pracownicy_has_spotkania", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_polish_ci");
                });

            modelBuilder.Entity("Meetings.Models.Działy", b =>
                {
                    b.HasOne("Meetings.Models.Filie", "IdFiliiNavigation")
                        .WithMany("Działies")
                        .HasForeignKey("IdFilii")
                        .IsRequired()
                        .HasConstraintName("Działy_ibfk_1");

                    b.Navigation("IdFiliiNavigation");
                });

            modelBuilder.Entity("Meetings.Models.Grafik", b =>
                {
                    b.HasOne("Meetings.Models.Pracownik", "IdPracownikaNavigation")
                        .WithMany("Grafiks")
                        .HasForeignKey("IdPracownika")
                        .IsRequired()
                        .HasConstraintName("fk_idPracownika");

                    b.Navigation("IdPracownikaNavigation");
                });

            modelBuilder.Entity("Meetings.Models.Pracownik", b =>
                {
                    b.HasOne("Meetings.Models.Działy", "IdDzialuNavigation")
                        .WithMany("Pracownicies")
                        .HasForeignKey("IdDzialu")
                        .IsRequired()
                        .HasConstraintName("Pracownicy_ibfk_2");

                    b.HasOne("Meetings.Models.Filie", "IdFiliiNavigation")
                        .WithMany("Pracownicies")
                        .HasForeignKey("IdFilii")
                        .IsRequired()
                        .HasConstraintName("Pracownicy_ibfk_3");

                    b.Navigation("IdDzialuNavigation");

                    b.Navigation("IdFiliiNavigation");
                });

            modelBuilder.Entity("Meetings.Models.Spotkanie", b =>
                {
                    b.HasOne("Meetings.Models.Filie", "IdFiliiNavigation")
                        .WithMany("Spotkania")
                        .HasForeignKey("IdFilii")
                        .IsRequired()
                        .HasConstraintName("fk_idFilii");

                    b.HasOne("Meetings.Models.Sala", "IdSaliNavigation")
                        .WithMany("Spotkania")
                        .HasForeignKey("IdSali")
                        .IsRequired()
                        .HasConstraintName("fk_idSali");

                    b.Navigation("IdFiliiNavigation");

                    b.Navigation("IdSaliNavigation");
                });

            modelBuilder.Entity("PracownicyHasSpotkanium", b =>
                {
                    b.HasOne("Meetings.Models.Pracownik", null)
                        .WithMany()
                        .HasForeignKey("IdPracownika")
                        .IsRequired()
                        .HasConstraintName("Pracownicy_has_Spotkania_ibfk_2");

                    b.HasOne("Meetings.Models.Spotkanie", null)
                        .WithMany()
                        .HasForeignKey("IdSpotkania")
                        .IsRequired()
                        .HasConstraintName("Pracownicy_has_Spotkania_ibfk_1");
                });

            modelBuilder.Entity("Meetings.Models.Działy", b =>
                {
                    b.Navigation("Pracownicies");
                });

            modelBuilder.Entity("Meetings.Models.Filie", b =>
                {
                    b.Navigation("Działies");

                    b.Navigation("Pracownicies");

                    b.Navigation("Spotkania");
                });

            modelBuilder.Entity("Meetings.Models.Pracownik", b =>
                {
                    b.Navigation("Grafiks");
                });

            modelBuilder.Entity("Meetings.Models.Sala", b =>
                {
                    b.Navigation("Spotkania");
                });
#pragma warning restore 612, 618
        }
    }
}
